CREATE TABLE KHACH_HANG(
	MA_KH INT(11),
    TEN_KH VARCHAR(40),
    DIA_CHI VARCHAR(100)
);
DROP TABLE SAN_PHAM;

TRUNCATE TABLE KHACH_HANG;

 #THÊM HÀNG GIỚI TÍNH
ALTER TABLE KHACH_HANG
ADD GIOI_TINH VARCHAR(5);

 #XOÁ HÀNG GIỚI TÍNH
ALTER TABLE KHACH_HANG
DROP COLUMN GIOI_TINH;

#THAY ĐỔI KIỂU DỮ LIỆU TRONG BẢNG
ALTER TABLE KHACH_HANG
MODIFY COLUMN TEN_KH VARCHAR(100);

#SET DỮ LIỆU CHO BẢNG TUỲ CỘT MUỐN SET
INSERT INTO KHACH_HANG(MA_KH, TEN_KH, DIA_CHI)
VALUE(4, 'Huỳnh Chí Thật', 'Cà Mau');

INSERT INTO KHACH_HANG(MA_KH, TEN_KH)
VALUE(2, 'Huỳnh Chí Thật');

#TẮT SET MODE ĐỂ UPDATES BẢNG
SET SQL_SAFE_UPDATES = 0; 

#TẠI VỊ TRÍ MA_KH = 2 THÌ SET ĐỊA CHỈ LÀ CÀ MAU
UPDATE KHACH_HANG
SET DIA_CHI = 'Cà Mau'
WHERE MA_KH = 2; 

# SET FULL ĐỊA CHỈ LÀ CÀ MAU 1
UPDATE KHACH_HANG
SET DIA_CHI = 'Cà Mau 1' ;

# XOÁ DỮ LIỆU TRÊN BẢNG CÓ DÒNG
DELETE FROM KHACH_HANG
WHERE MA_KH = 1;

# XOÁ ALL DỮ LIỆU TRÊN BẢNG
DELETE FROM KHACH_HANG;

####SELECT: TRUY XUẤT TỪ CSDL VÀ TRẢ VỀ KẾT QUẢ
#Trả về tất cả giá trị trong bảng
SELECT * FROM khach_hang;

#Lấy dữ liệu các cột từ bảng
SELECT MA_KH, DIA_CHI FROM khach_hang;

#Trả về các giá trị khác nhau
SELECT DISTINCT MA_KH, DIA_CHI FROM KHACH_HANG;

#SQL ALIAS: ĐẶT TÊN CHO CỘT TRẢ VỀ, BẢNG TRẢ VỀ
#ĐẶT TÊN CHO CỘT TRẢ VỀ
SELECT MA_KH AS 'Mã khách hàng', DIA_CHI AS 'Địa chỉ' FROM KHACH_HANG;

#ĐẠT TÊN CHO BẢNG TRẢ VỀ
SELECT T1.TEN_KH FROM KHACH_HANG AS T1;
SELECT T1.TEN_KH AS 'Tên Khách Hàng' FROM KHACH_HANG AS T1;


SELECT T1.TEN_KH AS 'Tên Khách Hàng', T1.DIA_CHI FROM KHACH_HANG AS T1
WHERE MA_KH = 1;

